#!/bin/bash

echo "🔧 Railway CORS Configuration Update"
echo "====================================="
echo ""
echo "Your app is running on these URLs:"
echo "  • iOS Simulator: exp://10.25.17.4:8097"
echo "  • Web: http://localhost:8097"
echo "  • Expo Go: exp://localhost:8097"
echo ""
echo "📝 To fix the CORS issue, update your Railway environment variables:"
echo ""
echo "1. Go to: https://railway.app"
echo "2. Select your project: generativemoodtracker-production"
echo "3. Go to Variables tab"
echo "4. Update ALLOWED_ORIGINS to:"
echo ""
echo "ALLOWED_ORIGINS=http://localhost:8097,http://localhost:3000,http://localhost:19006,exp://10.25.17.4:8097,exp://localhost:8097,exp://127.0.0.1:8097"
echo ""
echo "OR for development (more permissive):"
echo "ALLOWED_ORIGINS=*"
echo ""
echo "5. Save the changes"
echo "6. Railway will automatically redeploy"
echo ""
echo "🔄 After updating, restart your app and try again!"
echo ""
echo "🧪 Test the connection:"
echo "curl https://generativemoodtracker-production.up.railway.app/api/health" 